services:
    sq:
        container_name: sq
        image: sonarqube
        depends_on:
            - mssql
        environment:
            - sq_JDBC_USERNAME=sq
            - sq_JDBC_PASSWORD=sq
            - sq_JDBC_URL=jdbc:sqlserver://mssql:1433;databaseName=sq
        volumes:
            - sq_conf:/opt/sq/conf
            - sq_data:/opt/sq/data
            - sq_extensions:/opt/sq/extensions
            - sq_bundled-plugins:/opt/sq/lib/bundled-plugins
        ports:
            - 9000:9000

    mssql:
        container_name: mssql
        image:  mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=ThisIsMyPassword123!
            - MSSQL_PID=Express
        volumes:
            - sq_database_data:/var/opt/mssql/data
        ports:
            - 1433:1433

volumes:
    sq_bundled-plugins:
    sq_conf:
    sq_data:
    sq_database_data:
    sq_extensions:
